# SPDX-FileCopyrightText: 2023 Nikita Chernyi
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Redmine installation tasks
  tags:
    - setup-all
    - setup-redmine
    - install-all
    - install-redmine
  block:
    - name: Validate Redmine configuration
      when: redmine_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Redmine
      when: redmine_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Redmine uninstallation tasks
  tags:
    - setup-all
    - setup-redmine
  block:
    - name: Uninstall Redmine
      when: not redmine_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
